# 1. 기본적인 DNN

# 2. 사이킷런(sklearn) 이용
- 원핫인코딩을 하지 않고 라벨인코딩까지만 해야 작동. 원핫인코딩은 작동되지 않음

In [1]:
from sklearn import datasets # iris데이터
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [28]:
# 1. 데이터
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print(iris_X[::50], iris_y[::50])
train_X, test_X, train_y, test_y = train_test_split(iris_X, iris_y, 
                                                   test_size=0.1,  # 기본값은 train:test = 0.75:0.25
                                                   random_state=4,
                                                   stratify=iris_y)
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]] [0 1 2]
(135, 4) (135,) (15, 4) (15,)


In [45]:
# 사이킷런에서 제공하는 다층퍼셉트론 기반의 분류 알고리즘 api
mlp = MLPClassifier(hidden_layer_sizes=(50, 30),
                   activation='relu', 
                   solver='adam', # optimizer 설정값
                   max_iter =1000, # 최대학습횟수
                    early_stopping=True, # 조기 종료 활성화
                    n_iter_no_change=150, # 검증셋 손실함수가 개선되지 않으면 조기종료
                    validation_fraction=0.1 ) # 검증셋 비율

In [46]:
mlp.fit(train_X, train_y)

MLPClassifier(early_stopping=True, hidden_layer_sizes=(50, 30), max_iter=1000,
              n_iter_no_change=150)

In [47]:
mlp.score(test_X, test_y)

1.0

In [48]:
mlp.predict(test_X[0:1])

array([0])

# 3. 클래스를 생성

In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt

In [50]:
class DNNClassifier :
    @staticmethod
    def build(input_dim=4, activation='relu', output_dim=3):
#         model = Sequential()
#         model.add(Input(input_dim,))
#         model.add(Dense(50, activation=activation))
#         model.add(Dense(30, activation=activation))
#         model.add(Dense(output_dim, activation='softmax'))
        model = Sequential([
            Input(input_dim,),
            Dense(50, activation=activation),
            Dense(30, activation=activation),
            Dense(output_dim, activation='softmax'),
        ])
        #학습 과정 설정
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model

In [53]:
# 1. 데이터 생성 및 전처리
# iris_Y = pd.get_dummies(iris_y).to_numpy()
# # print(iris_Y[::50])  # 원핫인코딩
# train_X, test_X, train_Y, test_Y = train_test_split(iris_X, iris_Y,  # 원핫인코딩한 데이터로 분류
#                                                    test_size=0.1,    # 기본값은 train:test = 0.75:0.25
#                                                    random_state=4,
#                                                    stratify=iris_y)
# print(train_X.shape, train_Y.shape, test_X.shape, test_Y.shape)
train_Y = pd.get_dummies(train_y).values
test_Y = pd.get_dummies(test_y).values

# 2. 모델 생성
# model = DNNClassifier.build()  # 클래스를 생성하여 기본값을 쓰지 않아도 됨
model = DNNClassifier.build(input_dim=4, activation='relu', output_dim=3)

# 3. 모델 학습
earlystopping = EarlyStopping(patience=150)
hist = model.fit(train_X, train_Y, epochs=1000, validation_split=0.1,
                callbacks=[earlystopping])

Epoch 1/1000
4/4 [==============================] - 0s 55ms/step - loss: 1.6764 - accuracy: 0.3471 - val_loss: 1.3676 - val_accuracy: 0.2143
Epoch 2/1000
4/4 [==============================] - 0s 16ms/step - loss: 1.3290 - accuracy: 0.3471 - val_loss: 1.1137 - val_accuracy: 0.2143
Epoch 3/1000
4/4 [==============================] - 0s 17ms/step - loss: 1.1436 - accuracy: 0.3471 - val_loss: 0.9939 - val_accuracy: 0.2143
Epoch 4/1000
4/4 [==============================] - 0s 17ms/step - loss: 1.0484 - accuracy: 0.3471 - val_loss: 0.9339 - val_accuracy: 0.7857
Epoch 5/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.9925 - accuracy: 0.6364 - val_loss: 0.9047 - val_accuracy: 0.8571
Epoch 6/1000
4/4 [==============================] - 0s 16ms/step - loss: 0.9557 - accuracy: 0.7934 - val_loss: 0.8905 - val_accuracy: 0.9286
Epoch 7/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.9201 - accuracy: 0.9008 - val_loss: 0.8744 - val_accuracy: 0.8571
Epoch 8/1000


Epoch 59/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.2339 - accuracy: 0.9835 - val_loss: 0.1989 - val_accuracy: 0.9286
Epoch 60/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.2283 - accuracy: 0.9835 - val_loss: 0.1964 - val_accuracy: 0.9286
Epoch 61/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.2233 - accuracy: 0.9752 - val_loss: 0.1951 - val_accuracy: 0.9286
Epoch 62/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.2178 - accuracy: 0.9752 - val_loss: 0.1925 - val_accuracy: 0.9286
Epoch 63/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.2126 - accuracy: 0.9835 - val_loss: 0.1889 - val_accuracy: 0.9286
Epoch 64/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.2089 - accuracy: 0.9917 - val_loss: 0.1855 - val_accuracy: 0.9286
Epoch 65/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.2037 - accuracy: 0.9835 - val_loss: 0.1872 - val_accuracy: 0.9286
Epoch 

4/4 [==============================] - 0s 13ms/step - loss: 0.0867 - accuracy: 0.9917 - val_loss: 0.1297 - val_accuracy: 0.9286
Epoch 117/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0871 - accuracy: 0.9917 - val_loss: 0.1319 - val_accuracy: 0.9286
Epoch 118/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0924 - accuracy: 0.9917 - val_loss: 0.1274 - val_accuracy: 0.8571
Epoch 119/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0870 - accuracy: 0.9917 - val_loss: 0.1369 - val_accuracy: 0.9286
Epoch 120/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0845 - accuracy: 0.9835 - val_loss: 0.1317 - val_accuracy: 0.9286
Epoch 121/1000
4/4 [==============================] - 0s 17ms/step - loss: 0.0824 - accuracy: 0.9917 - val_loss: 0.1287 - val_accuracy: 0.9286
Epoch 122/1000
4/4 [==============================] - 0s 16ms/step - loss: 0.0841 - accuracy: 0.9917 - val_loss: 0.1268 - val_accuracy: 0.8571
Epoch 123/1000

4/4 [==============================] - 0s 17ms/step - loss: 0.0606 - accuracy: 0.9917 - val_loss: 0.1241 - val_accuracy: 0.8571
Epoch 174/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0611 - accuracy: 0.9917 - val_loss: 0.1247 - val_accuracy: 0.9286
Epoch 175/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0605 - accuracy: 0.9917 - val_loss: 0.1236 - val_accuracy: 0.8571
Epoch 176/1000
4/4 [==============================] - 0s 17ms/step - loss: 0.0607 - accuracy: 0.9917 - val_loss: 0.1246 - val_accuracy: 0.8571
Epoch 177/1000
4/4 [==============================] - 0s 17ms/step - loss: 0.0611 - accuracy: 0.9917 - val_loss: 0.1282 - val_accuracy: 0.9286
Epoch 178/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0603 - accuracy: 0.9917 - val_loss: 0.1251 - val_accuracy: 0.9286
Epoch 179/1000
4/4 [==============================] - 0s 10ms/step - loss: 0.0609 - accuracy: 0.9917 - val_loss: 0.1244 - val_accuracy: 0.8571
Epoch 180/1000

4/4 [==============================] - 0s 17ms/step - loss: 0.0549 - accuracy: 0.9917 - val_loss: 0.1299 - val_accuracy: 0.8571
Epoch 231/1000
4/4 [==============================] - 0s 17ms/step - loss: 0.0533 - accuracy: 0.9917 - val_loss: 0.1318 - val_accuracy: 0.9286
Epoch 232/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0528 - accuracy: 0.9917 - val_loss: 0.1285 - val_accuracy: 0.8571
Epoch 233/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0522 - accuracy: 0.9917 - val_loss: 0.1287 - val_accuracy: 0.8571
Epoch 234/1000
4/4 [==============================] - 0s 19ms/step - loss: 0.0527 - accuracy: 0.9917 - val_loss: 0.1299 - val_accuracy: 0.8571
Epoch 235/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0522 - accuracy: 0.9917 - val_loss: 0.1366 - val_accuracy: 0.9286
Epoch 236/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0544 - accuracy: 0.9917 - val_loss: 0.1354 - val_accuracy: 0.9286
Epoch 237/1000

4/4 [==============================] - 0s 16ms/step - loss: 0.0477 - accuracy: 0.9917 - val_loss: 0.1359 - val_accuracy: 0.8571
Epoch 288/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0482 - accuracy: 0.9917 - val_loss: 0.1352 - val_accuracy: 0.8571
Epoch 289/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0483 - accuracy: 0.9917 - val_loss: 0.1364 - val_accuracy: 0.8571
Epoch 290/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0474 - accuracy: 0.9917 - val_loss: 0.1364 - val_accuracy: 0.8571
Epoch 291/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0475 - accuracy: 0.9917 - val_loss: 0.1362 - val_accuracy: 0.8571
Epoch 292/1000
4/4 [==============================] - 0s 15ms/step - loss: 0.0497 - accuracy: 0.9917 - val_loss: 0.1384 - val_accuracy: 0.8571
Epoch 293/1000
4/4 [==============================] - 0s 15ms/step - loss: 0.0475 - accuracy: 0.9917 - val_loss: 0.1361 - val_accuracy: 0.8571
Epoch 294/1000

In [57]:
loss, accuracy = model.evaluate(test_X, test_Y)
print(f'정확도: {accuracy*100}%')

1/1 [==============================] - 0s 23ms/step - loss: 0.0536 - accuracy: 0.9333
정확도: 93.33333373069763%


In [59]:
model.predict(test_X[0].reshape(1,-1)).argmax(axis=1)

1/1 [==============================] - 0s 86ms/step


array([0], dtype=int64)

# 4. 함수 : 병렬처리

In [64]:
from tensorflow.keras.layers import concatenate
from tensorflow.keras import Model

In [65]:
train_X.shape, train_Y.shape, test_X.shape, test_Y.shape

((135, 4), (135, 3), (15, 4), (15, 3))

In [67]:
# 모델
input_ = Input(shape=(4, )) # input 레이어
dense1 = Dense(units=50, activation='relu')(input_)
dense2 = Dense(units=80, activation='relu')(input_)
dense3 = Dense(units=30, activation='relu')(input_)
x = concatenate([dense1, dense2, dense3])
# x = Dense(units=160, activation='relu')(input_) 의 병렬처리 구현
output = Dense(units=3, activation='softmax')(x)
model = Model(inputs=input_, outputs=output)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_10 (InputLayer)          [(None, 4)]          0           []                               
                                                                                                  
 dense_30 (Dense)               (None, 50)           250         ['input_10[0][0]']               
                                                                                                  
 dense_31 (Dense)               (None, 80)           400         ['input_10[0][0]']               
                                                                                                  
 dense_32 (Dense)               (None, 30)           150         ['input_10[0][0]']               
                                                                                              

In [71]:
# 학습 정의(설정), 학습
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])
model.fit(train_X, train_Y,
         epochs=200,
         verbose=1)

Epoch 1/200
5/5 [==============================] - 0s 8ms/step - loss: 1.7682 - accuracy: 0.3333
Epoch 2/200
5/5 [==============================] - 0s 9ms/step - loss: 1.2638 - accuracy: 0.2667
Epoch 3/200
5/5 [==============================] - 0s 4ms/step - loss: 1.0358 - accuracy: 0.6074
Epoch 4/200
5/5 [==============================] - 0s 9ms/step - loss: 0.9867 - accuracy: 0.3333
Epoch 5/200
5/5 [==============================] - 0s 9ms/step - loss: 0.9198 - accuracy: 0.5926
Epoch 6/200
5/5 [==============================] - 0s 8ms/step - loss: 0.8243 - accuracy: 0.6741
Epoch 7/200
5/5 [==============================] - 0s 4ms/step - loss: 0.7646 - accuracy: 0.9111
Epoch 8/200
5/5 [==============================] - 0s 4ms/step - loss: 0.7192 - accuracy: 0.8815
Epoch 9/200
5/5 [==============================] - 0s 4ms/step - loss: 0.6727 - accuracy: 0.9259
Epoch 10/200
5/5 [==============================] - 0s 4ms/step - loss: 0.6295 - accuracy: 0.8148
Epoch 11/200
5/5 [===========

5/5 [==============================] - 0s 4ms/step - loss: 0.1612 - accuracy: 0.9778
Epoch 85/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1629 - accuracy: 0.9704
Epoch 86/200
5/5 [==============================] - 0s 5ms/step - loss: 0.1597 - accuracy: 0.9778
Epoch 87/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1568 - accuracy: 0.9852
Epoch 88/200
5/5 [==============================] - 0s 5ms/step - loss: 0.1566 - accuracy: 0.9704
Epoch 89/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1543 - accuracy: 0.9778
Epoch 90/200
5/5 [==============================] - 0s 5ms/step - loss: 0.1516 - accuracy: 0.9852
Epoch 91/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1551 - accuracy: 0.9704
Epoch 92/200
5/5 [==============================] - 0s 4ms/step - loss: 0.1502 - accuracy: 0.9704
Epoch 93/200
5/5 [==============================] - 0s 3ms/step - loss: 0.1472 - accuracy: 0.9852
Epoch 94/200
5/5 [===============

5/5 [==============================] - 0s 5ms/step - loss: 0.0912 - accuracy: 0.9852
Epoch 168/200
5/5 [==============================] - 0s 4ms/step - loss: 0.0914 - accuracy: 0.9852
Epoch 169/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0904 - accuracy: 0.9852
Epoch 170/200
5/5 [==============================] - 0s 4ms/step - loss: 0.0908 - accuracy: 0.9852
Epoch 171/200
5/5 [==============================] - 0s 4ms/step - loss: 0.0903 - accuracy: 0.9852
Epoch 172/200
5/5 [==============================] - 0s 4ms/step - loss: 0.0903 - accuracy: 0.9852
Epoch 173/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0891 - accuracy: 0.9778
Epoch 174/200
5/5 [==============================] - 0s 5ms/step - loss: 0.0883 - accuracy: 0.9852
Epoch 175/200
5/5 [==============================] - 0s 4ms/step - loss: 0.0890 - accuracy: 0.9778
Epoch 176/200
5/5 [==============================] - 0s 5ms/step - loss: 0.0908 - accuracy: 0.9852
Epoch 177/200
5/5 [=====

In [73]:
# 학습평가
loss, accuracy = model.evaluate(test_X, test_Y)
print(accuracy*100,'%')

1/1 [==============================] - 0s 109ms/step - loss: 0.0935 - accuracy: 0.9333
93.33333373069763 %
