<b><font color="red" size="6"> ch11. N차원 배열 다루기 </font></b>
# 4절 복사와 뷰
## 4.1 할당

In [3]:
# 스칼라 변수
a = 10
b = a
print('a와 b주소 :',id(a), id(b))
b = 99
print('수정후 a와 b주소 :', id(a), id(b))
print('수정후 a와 b 데이터 : ',a,b)

a와 b주소 : 1436575662608 1436575662608
수정후 a와 b주소 : 1436575662608 1436575665456
수정후 a와 b 데이터 :  10 99


In [29]:
# 배열
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = a

In [31]:
a.shape, type(a), a.ndim, id(a)

((12,), numpy.ndarray, 1, 1434541243344)

In [32]:
b.shape, type(b), b.ndim, id(b)

((12,), numpy.ndarray, 1, 1434541243344)

In [33]:
a is b

True

In [34]:
a==b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [35]:
all(a==b)

True

In [36]:
b.shape = (3, 4)

In [37]:
a.shape, type(a), a.ndim, id(a)

((3, 4), numpy.ndarray, 2, 1434541243344)

## 4.2 뷰(View) : 얕은복사

In [53]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
c==a

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [56]:
np.all(c==a)

True

In [57]:
c is a

False

In [58]:
c.shape = (2, 6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
# 배열 c의 특정 요소만 변경(1행의 짝수번째 열 변경)
c[1,::2] = -9
c

array([[ 0,  1,  2,  3,  4,  5],
       [-9,  7, -9,  9, -9, 11]])

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -9,  7],
       [-9,  9, -9, 11]])

In [68]:
# 슬라이싱이 될 때 뷰가 반환됨
a = np.array([[1, 85, 2015, 5000],
             [1, 102, 2015, 5500],
             [2, 45, 2016, 4900],])
a

array([[   1,   85, 2015, 5000],
       [   1,  102, 2015, 5500],
       [   2,   45, 2016, 4900]])

In [70]:
X = a[:,:-1] # 독립변수를 슬라이싱해서 X대입 : 슬라이싱될 때 뷰가 반환
X

array([[   1,   85, 2015],
       [   1,  102, 2015],
       [   2,   45, 2016]])

In [71]:
X[0:2, -1]= 1
X[-1,-1] = 2
X

array([[  1,  85,   1],
       [  1, 102,   1],
       [  2,  45,   2]])

In [72]:
a

array([[   1,   85,    1, 5000],
       [   1,  102,    1, 5500],
       [   2,   45,    2, 4900]])

## 4.3 깊은 복사

In [73]:
# 슬라이싱이 될 때 뷰가 반환됨
a = np.array([[1, 85, 2015, 5000],
             [1, 102, 2015, 5500],
             [2, 45, 2016, 4900],])
a

array([[   1,   85, 2015, 5000],
       [   1,  102, 2015, 5500],
       [   2,   45, 2016, 4900]])

In [76]:
# X = a[:,:-1] # 얕은복사
X = a[:, :-1].copy() #깊은복사
X

array([[   1,   85, 2015],
       [   1,  102, 2015],
       [   2,   45, 2016]])

In [77]:
X[:,0:-1] = 1
X[-1, -1] = 2
X

array([[   1,    1, 2015],
       [   1,    1, 2015],
       [   1,    1,    2]])

In [78]:
a

array([[   1,   85, 2015, 5000],
       [   1,  102, 2015, 5500],
       [   2,   45, 2016, 4900]])

# 5절. 고급인덱싱
## 5.1 인덱스 배열로 인덱싱

In [79]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [81]:
a[[0, 5, 9]]

array([ 0, 25, 81])

In [85]:
# 인덱싱하기 위한 값을 배열로 만듦
i = np.array([0, 0, 5, 9])
a[i] # 결과는 i(인덱싱 배열)의 형태로 따라감

array([ 0,  0, 25, 81])

In [86]:
# 인덱싱 하기 위한 값을 배열로 만듦
j = np.array([[0,1],
             [1,5]])
a[j]

array([[ 0,  1],
       [ 1, 25]])

In [89]:
a[j] += 100
a

array([300, 301,   4,   9,  16, 325,  36,  49,  64,  81, 100, 121])

In [90]:
                    #R G B
palette = np.array([[0,0,0], # black
                   [255,0,0], # red
                   [0,255,0], # green
                   [0,0,255], # blue
                   [255,255,255]])  #white 

In [92]:
image_index = np.array([[4,4,4,0,0,0,0,4,4,4],
                        [4,0,0,4,4,4,4,0,0,4],
                        [0,0,4,4,4,4,4,4,0,0],
                        [0,4,4,1,4,4,3,4,4,0],
                        [0,4,4,1,4,4,3,4,4,0],
                        [0,4,4,4,4,4,4,4,4,0],
                        [0,4,4,2,4,4,2,4,4,0],
                        [4,0,4,4,2,2,4,4,0,4],
                        [4,4,0,4,4,4,4,0,4,4],
                        [4,4,4,0,0,0,0,4,4,4]])
image_data = palette[image_index]
image_data

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [255,   0,   0],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0, 255],
        [255, 255, 255],
        [255, 255, 255],
        [  0,   0, 

In [93]:
image_data.shape

(10, 10, 3)

In [1]:
# from matplotlib.pyplot as plt
from matplotlib import pyplot as plt
plt.figure(figsize=(2,2))
plt.imshow(image_data)
plt.show()


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\201-23\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\201-23\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\201-23\anaconda3\lib\site

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import

In [1]:
# 나중에 학습할 이미지 데이터
import numpy as np

In [2]:
import tensorflow as tf
tf.__version__


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\201-23\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\201-23\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\201-23\anaconda3\lib\site

AttributeError: _ARRAY_API not found


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\201-23\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\201-23\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\201-23\anaconda3\lib\site

AttributeError: _ARRAY_API not found

ImportError: numpy.core._multiarray_umath failed to import

ImportError: numpy.core.umath failed to import

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [3]:
import tensorflow.keras.datasets.mnist as mnist
mnist = mnist.load_data

TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle

In [ ]:
mnist[0][0] # 독립변수가 될 이미지들 60000

In [ ]:
mnist[0][1] # 종속변수

In [ ]:
X = mnist[0][0]
Y = mnist[0][1]

In [ ]:
plt.imshow(X[57217])
plt.show()

In [ ]:
Y[57217]

# 5.2 argmax : 최대값이 있는 인덱스

In [5]:
import numpy as np
data = np.sin(np.arange(20).reshape(5,4))
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [8]:
ind = data.argmax(axis=0) # 각 열별 큰 값이 있는 index위치
ind

array([2, 0, 3, 1])

In [10]:
# 0열에서의 최대값, 1열에서의 최대값, 2열에서의 최대값
data[ind[0],0], data[ind[1],1]

(np.float64(0.9893582466233818), np.float64(0.8414709848078965))

In [11]:
data.shape

(5, 4)

In [16]:
data_col_max = data[ind,range(data.shape[1])]
data_col_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [18]:
np.all(data_col_max == data.max(axis=0))

np.True_

## 5.3 논리 배열을 이용한 인덱싱

In [19]:
a = np.arange(20).reshape(2, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [20]:
a[a%2==0] # 논리 배열을 이용한 인덱싱시 True 요소만 추출

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
a[a>15]

array([16, 17, 18, 19])

# 6절. 선형대수
- 2차원 넘파이 배열을 행렬
    * 행렬곱 : @ . np.dot()
    * 역행렬 : np.linalg.inv(X)
    * 전치행렬 : X.T, X.transpose()
    * 단위행렬 : np.eye(n) : n행n열 단위행렬

In [4]:
a = np.array([[1,2],
             [3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
# a의 역행렬 : a의 역행렬과 @ a =  단위행렬
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [6]:
np.linalg.inv(a)@ a

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [7]:
np.eye(2) # 2행 2열짜리 단위행렬

array([[1., 0.],
       [0., 1.]])

In [11]:
np.linalg.inv(a) @ a == np.eye(2)

array([[False,  True],
       [False,  True]])

# 6.1 선형 연립 방정식 풀기(단별량 회귀분석) : 독립변수1, 데이터 2개

In [12]:
x = np.array([2,4]) # 독립변수 학습데이터는 array로
Y = np.array([40,60]) # 종속변수
X = np.dstack( (x, np.ones(len(x))))
X

array([[[2., 1.],
        [4., 1.]]])

In [13]:
# X @ wb = Y
# X의 역행렬 @ X @ wb = X의 역행렬 @ Y
# wb = X의 역행렬 @ Y

In [14]:
wb = np.linalg.inv(X) @ Y
wb

array([[10., 20.]])

In [19]:
import matplotlib.pyplot as plt
plt.scatter(x, Y, c='b')
plt.plot(x, 10*x+20, color='r')
plt.show()


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\201-23\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\201-23\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\201-23\anaconda3\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance
    app.start()
  File "C:\Users\201-23\anaconda3\lib\site

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import